name: Scheduling the workflow
on:
    schedule:
        - cron: "0/5 * * * *"

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v8
              with:
                stale-issue-message: "this is test"
                days-before-stale: 2
                days-before-close: 5