name: checking events
on:
    push:
    pull_request:
        types: [opened, closed, edited]
    issues: 
        types: [opened]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: printing repo
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
                echo "this is new"
            - uses: actions/checkout@v3
