name: Expression and contexts
on: [push, pull_request]

jobs:
    expression-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: expression
              run: |
                 echo ${{ 1 }}
                 echo ${{ 'this is string' }}
            - name: Dump contexts
              run: |
                echo '${{ toJson(job) }}'
                echo '${{ toJson(runner) }}'