name: Expression and contexts
on: [push, pull_request, issues]
run-name: "Expressions and context by @${{ github.actor }} and event: ${{ github.event_name }}"

jobs:
    expression-with-if:
        runs-on: ubuntu-latest
        if: contains(fromJson('["issues"]'), github.event_name)
        steps:
            - name: Run only if issues has bug label
              if: contains(github.event.issue.labels.*.name, 'bug')
              run: echo ${{ join(github.event.issue.labels.*.name, ',') }}
              
    expression-contexts:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: expression
              run: |
                 echo ${{ 1 }}
                 echo ${{ 'this is string' }}
            - name: Dump contexts
              run: |
                echo '${{ toJson(job) }}'
                echo '${{ toJson(runner) }}'