name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps: 
            - name: run echo command
              run: echo "Hello Suresh"
            - name: run multiline 
              run: |
                 echo " hellow world"
                 node -v
                 pwd
                 npm -v
                 docker -v
    depends-job:
        runs-on: windows-lates
        needs: run-on-macos
        steps:
            - name: print outpot
              run: Write-Output " windows string"
            - name: error
              run: doesnotexist
    run-on-macos:
        runs-on: macos-latest
        steps:
            - name: check software version
              run: sw_vers