name: manual trigger
on:
    workflow_dispatch:
        inputs:
            string:
                description: A string value
                type: string
                default: "please eneter a value"
            option:
                type: choice
                required: true
                options:
                    - option 1
                    - option 2
                    - option 3

jobs:
    login-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: |
               echo ${{ inputs.string }}
               echo ${{ inputs.option }}
