name: comment on the pull request 
on:
    pull_request_target:
        types: [opened, closed]
        branches: 
            - 'feature/**'
jobs:
    pr-comment:
        runs-on: ubuntu-latest
        steps:
            - name: comment on pull request
              uses: actions/github-script@v6
              with:
                script: |
                  github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'Thanks for pull request ! ',
                  });
