name: Testing git actions
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: shell comds
              run: pwd
            - name: list files
              run: |
                 touch test.txt
                 ls -lrth
                 echo $GITHUB_SHA
                 echo "---------"
                 echo $GITHUB_WORKSPACE
                 echo "------------"
                 echo $GITHUB_REPOSITORY
